import { atom } from "recoil";
import { dateSmall } from "../../../3organisms/Org_adminTable/fn_DateSmall";
import { IColumn } from "../../../3organisms/Org_adminTable2/interface_column";

const nowDate = dateSmall(new Date());
export const questionColumnsDefault: IColumn[] = [
  {
    Header: "생성일",
    accessor: "createdAt",
    width: 130,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "detailDate",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "멘션",
    accessor: "rawMention",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "새창",
    accessor: "newPage",
    width: 64,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "newPage",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "브랜드명(R)",
    accessor: "brandName_partner",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "브랜드명*",
    accessor: "brandName",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: true,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "제품",
    accessor: "product",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "문의서비스",
    accessor: "serviceInquired",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "분석유무",
    accessor: "isAnalyzed",
    width: 150,
    sortDescFirst: true,
    value: "X",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
  },
  {
    Header: "이름*",
    accessor: "name",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "연락처*",
    accessor: "phoneNumber",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "이메일*",
    accessor: "email",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "예산",
    accessor: "budget",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "제품 링크",
    accessor: "productLink",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "문의사항",
    accessor: "uniqueness",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "textarea",
    formType_edit: "textarea",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "대행사",
    accessor: "isAgency",
    width: 150,
    sortDescFirst: true,
    value: "X",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
  },
  {
    Header: "태그",
    accessor: "tags",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "결제 예정일",
    accessor: "paymentDueDate",
    width: 100,
    sortDescFirst: true,
    value: nowDate,
    selected: false,
    tableType: "date",
    formType_create: "date",
    formType_edit: "date",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "문의 담당자",
    accessor: "contactPerson_nickname",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "dataId",
    accessor: "id",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "number",
    editable: false,
  },
  {
    Header: "newPageId",
    accessor: "newPageId",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
];

export const rawQuestionColumnsAtom = atom({
  key: "rawQuestionColumnsAtom",
  default: questionColumnsDefault,
});
