import { atom, useRecoilState } from "recoil";
import { IColumn } from "../../../3organisms/Org_adminTable2/interface_column";

export const adminColumnsDefault: IColumn[] = [
  {
    Header: "생성일",
    accessor: "createdAt",
    width: 87,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "date",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "이메일(ID)",
    accessor: "email",
    width: 400,
    sortDescFirst: true,
    value: "",
    selected: true,
    tableType: "string",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "닉네임",
    accessor: "nickname",
    width: 300,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },

  {
    Header: "역할",
    accessor: "role",
    width: 120,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "translate",
    translate: [
      { key: "General", value: "일반" },
      { key: "Super", value: "슈퍼" },
    ],
    formType_create: "select",
    formType_edit: "select",
    formSelectList: ["일반", "슈퍼"],
    mutationType_create: "translate",
    mutationType_edit: "translate",
    editable: true,
  },
  {
    Header: "dataId",
    accessor: "id",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "number",
    editable: false,
  },
];

export const rawAdminColumnsData = atom({
  key: "rawAdminColumnsData",
  default: adminColumnsDefault,
});
