import { atom, useRecoilState } from "recoil";
import { dateSmall } from "../../../3organisms/Org_adminTable/fn_DateSmall";
import { IColumn } from "../../../3organisms/Org_adminTable2/interface_column";

const nowDate = dateSmall(new Date());
export const questionManagementColumnsDefault: IColumn[] = [
  {
    Header: "생성일",
    accessor: "createdAt",
    width: 87,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "date",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "멘션",
    accessor: "rawMention",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "새창",
    accessor: "newPage",
    width: 64,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "newPage",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "브랜드명",
    accessor: "brandName",
    width: 200,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: true,
  },
  {
    Header: "스케쥴",
    accessor: "stateDate",
    value: nowDate,
    selected: false,
    width: 97,
    sortDescFirst: true,
    tableType: "date",
    formType_create: "date",
    formType_edit: "date",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "제목",
    accessor: "stateName",
    width: 200,
    sortDescFirst: true,
    value: "",
    selected: true,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "상태",
    accessor: "state",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "시간",
    accessor: "stateTime",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "비고",
    accessor: "note",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "textarea",
    formType_edit: "textarea",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "코멘트",
    accessor: "comment",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "textarea",
    formType_edit: "textarea",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "제품",
    accessor: "product",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: true,
  },
  {
    Header: "문의서비스",
    accessor: "serviceInquired",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: true,
  },
  {
    Header: "dataId",
    accessor: "id",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "number",
    editable: false,
  },
  {
    Header: "questionId",
    accessor: "questionId",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: false,
  },
];

export const rawQuestionManagementColumnsData = atom({
  key: "rawQuestionManagementColumnsData",
  default: questionManagementColumnsDefault,
});
