import { atom, useRecoilState } from "recoil";
import { IColumn } from "../../../3organisms/Org_adminTable2/interface_column";

export const userColumnsDefault: IColumn[] = [
  {
    Header: "생성일",
    accessor: "createdAt",
    width: 87,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "date",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "계정(ID)",
    accessor: "email",
    value: "",
    selected: true,
    width: 150,
    sortDescFirst: true,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "비밀번호",
    accessor: "password",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "password",
    formType_edit: "password",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "비밀번호 확인",
    accessor: "passwordCheck",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "password",
    formType_edit: "password",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: true,
  },
  {
    Header: "이름(ID)",
    accessor: "nameId",
    width: 110,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "이름",
    accessor: "name",
    width: 100,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "성별",
    accessor: "gender",
    width: 100,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "select",
    formType_edit: "select",
    formSelectList: ["", "남성", "여성"],
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "연락처",
    accessor: "phoneNumber",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "연락용 메일",
    accessor: "additionalEmail",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "주민등록번호",
    accessor: "residentRegistrationNumber",
    width: 160,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "네이버",
    accessor: "isNaverUser",
    width: 70,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
  },
  {
    Header: "인스타",
    accessor: "isInstaUser",
    width: 70,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
  },
  {
    Header: "태그",
    accessor: "tags",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "dataId",
    accessor: "id",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "number",
    editable: false,
  },
];

export const rawUserColumnsData = atom({
  key: "rawUserColumnsData",
  default: userColumnsDefault,
});
