import { atom } from "recoil";
import {
  NumberRangeColumnFilter,
  PointRangeColumnFilter,
  SelectColumnFilter,
} from "../../../3organisms/Org_adminTable2";
import { IColumn } from "../../../3organisms/Org_adminTable2/interface_column";

export const userColumnsDefault: IColumn[] = [
  {
    Header: "생성일",
    accessor: "createdAt",
    width: 87,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "date",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "계정(ID)",
    accessor: "email",
    value: "",
    selected: true,
    width: 150,
    sortDescFirst: true,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "비밀번호",
    accessor: "password",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "password",
    formType_edit: "password",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "비밀번호 확인",
    accessor: "passwordCheck",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "password",
    formType_edit: "password",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: true,
  },
  {
    Header: "이름(ID)",
    accessor: "nameId",
    width: 110,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "이름",
    accessor: "name",
    width: 100,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "성별",
    accessor: "gender",
    width: 70,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "select",
    formType_edit: "select",
    formSelectList: ["", "남성", "여성"],
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
    Filter: SelectColumnFilter,
  },
  {
    Header: "연락처",
    accessor: "phoneNumber",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "연락용 메일",
    accessor: "additionalEmail",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "직업",
    accessor: "job",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "주소지",
    accessor: "address",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "은행",
    accessor: "bank",
    width: 100,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "계좌번호",
    accessor: "accountNumber",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "주민등록번호",
    accessor: "residentRegistrationNumber",
    width: 160,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "신용 점수",
    accessor: "creditPoint",
    width: 70,
    sortDescFirst: true,
    value: 5,
    selected: false,
    tableType: "number",
    formType_create: "point",
    formType_edit: "point",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
    Filter: PointRangeColumnFilter,
    filter: "between",
  },
  {
    Header: "정성 점수",
    accessor: "qualitativePoint",
    width: 70,
    sortDescFirst: true,
    value: 5,
    selected: false,
    tableType: "number",
    formType_create: "point",
    formType_edit: "point",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
    Filter: PointRangeColumnFilter,
    filter: "between",
  },
  {
    Header: "경제 점수",
    accessor: "economyPoint",
    width: 70,
    sortDescFirst: true,
    value: 5,
    selected: false,
    tableType: "number",
    formType_create: "point",
    formType_edit: "point",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
    Filter: PointRangeColumnFilter,
    filter: "between",
  },
  {
    Header: "플친 여부",
    accessor: "isJoinedInPlusBuddy",
    width: 70,
    sortDescFirst: true,
    value: "X",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
    Filter: SelectColumnFilter,
  },
  {
    Header: "인스타 계정",
    accessor: "isInstaUser",
    width: 70,
    sortDescFirst: true,
    value: "X",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
    Filter: SelectColumnFilter,
  },
  {
    Header: "네이버 계정",
    accessor: "isNaverUser",
    width: 70,
    sortDescFirst: true,
    value: "X",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
    Filter: SelectColumnFilter,
  },
  {
    Header: "인스타 계정확인",
    accessor: "insta_isExisted",
    width: 70,
    sortDescFirst: true,
    value: "X",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
    Filter: SelectColumnFilter,
  },
  {
    Header: "인스타 아이디",
    accessor: "insta_id",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "팔로워",
    accessor: "insta_NumberOfFollowers",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "number",
    formType_create: "number",
    formType_edit: "number",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
    Filter: NumberRangeColumnFilter,
    filter: "between",
  },
  {
    Header: "동영상 제작",
    accessor: "insta_canMakeVideo",
    width: 70,
    sortDescFirst: true,
    value: "X",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
    Filter: SelectColumnFilter,
  },
  {
    Header: "카테고리1",
    accessor: "insta_category1",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "카테고리2",
    accessor: "insta_category2",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "스타일",
    accessor: "insta_style",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "전문점수",
    accessor: "insta_professionalPoint",
    width: 70,
    sortDescFirst: true,
    value: 5,
    selected: false,
    tableType: "number",
    formType_create: "point",
    formType_edit: "point",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
    Filter: PointRangeColumnFilter,
    filter: "between",
  },
  {
    Header: "건강점수",
    accessor: "insta_heathyPoint",
    width: 70,
    sortDescFirst: true,
    value: 5,
    selected: false,
    tableType: "number",
    formType_create: "point",
    formType_edit: "point",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
    Filter: PointRangeColumnFilter,
    filter: "between",
  },
  {
    Header: "지정가",
    accessor: "insta_designatedPrice",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "number",
    formType_create: "number",
    formType_edit: "number",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
  },
  {
    Header: "제안횟수",
    accessor: "insta_numberOfProposals",
    width: 70,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "number",
    formType_create: "number",
    formType_edit: "number",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
  },
  {
    Header: "참여율",
    accessor: "insta_participationRate",
    width: 70,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "number",
    formType_create: "number",
    formType_edit: "number",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
  },
  {
    Header: "네이버 계정확인",
    accessor: "naver_isExisted",
    width: 70,
    sortDescFirst: true,
    value: "X",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
    Filter: SelectColumnFilter,
  },
  {
    Header: "네이버 계정",
    accessor: "naver_id",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "일방문자",
    accessor: "naver_averageNumberOfVisitors",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "number",
    formType_create: "number",
    formType_edit: "number",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
  },
  {
    Header: "전체방문자",
    accessor: "naver_totalNumberOfVisitors",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "number",
    formType_create: "number",
    formType_edit: "number",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
  },
  {
    Header: "이웃수",
    accessor: "naver_numberOfBuddys",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "number",
    formType_create: "number",
    formType_edit: "number",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
  },
  {
    Header: "네이버 인플루언서 여부",
    accessor: "naver_isNaverInfluencer",
    width: 70,
    sortDescFirst: true,
    value: "X",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
    Filter: SelectColumnFilter,
  },
  {
    Header: "카테고리1",
    accessor: "naver_category1",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "카테고리2",
    accessor: "naver_category2",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "건강점수",
    accessor: "naver_heathyPoint",
    width: 70,
    sortDescFirst: true,
    value: 5,
    selected: false,
    tableType: "number",
    formType_create: "point",
    formType_edit: "point",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
    Filter: PointRangeColumnFilter,
    filter: "between",
  },
  {
    Header: "제안횟수",
    accessor: "naver_numberOfProposals",
    width: 70,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "number",
    formType_create: "number",
    formType_edit: "number",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
  },
  {
    Header: "참여율",
    accessor: "naver_participationRate",
    width: 70,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "number",
    formType_create: "number",
    formType_edit: "number",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
  },
  {
    Header: "태그",
    accessor: "tags",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "dataId",
    accessor: "id",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "number",
    editable: false,
  },
];

export const rawUserColumnsData = atom({
  key: "rawUserColumnsData",
  default: userColumnsDefault,
});
