export const naverUserColumns = [
  "createdAt",

  "nameId",
  "naver_averageNumberOfVisitors",
  "naver_totalNumberOfVisitors",
  "naver_numberOfBuddys",
  "naver_isNaverInfluencer",
  "naver_numberOfFans",
  "naver_category1",
  "naver_category2",

  "naver_heathyPoint",
  "creditPoint",
  "qualitativePoint",
  "economyPoint",
  "naver_numberOfProposals",
  "naver_participationRate",

  "insta_isInstaUser",
  "naver_isNaverUser",
  "naverIn_isNaverInfluencer",
  "isJoinedInPlusBuddy",
  "naver_isExisted",
  "naver_id",

  "naverIn_isExisted",
  "naverIn_id",
  "naverIn_numberOfFans",
  "naverIn_category1",
  "naverIn_category2",

  "email",
  "password",
  "passwordCheck",
  "name",
  "gender",
  "phoneNumber",
  "additionalEmail",
  "job",
  "address",
  "bank",
  "accountNumber",
  "residentRegistrationNumber",
  "tags",

  "id",
];
