import { atom, useRecoilState } from "recoil";
import { IColumn } from "../../../3organisms/Org_adminTable2/interface_column";
import { dateSmall } from "/home/app/components/3organisms/Org_adminTable/fn_DateSmall";

export const campaignExceptionData = {
  table: ["id"],
  createForm: ["id", "createdAt"],
  createMutation: ["id", "createdAt"],
  editForm: ["id", "createdAt"],
  editMutation: ["createdAt"],
  editBtn: ["id", "createdAt", "selection"],
  focusId: "brandName_partner",
};

const nowDate = dateSmall(new Date());
export const campaignColumnsDefault: IColumn[] = [
  {
    Header: "생성일",
    accessor: "createdAt",
    width: 87,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "매출일",
    accessor: "salesDate",
    width: 150,
    sortDescFirst: true,
    value: nowDate,
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "목표일",
    accessor: "targetDate",
    width: 150,
    sortDescFirst: true,
    value: nowDate,
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "브랜드명(R)",
    accessor: "brandName_partner",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "누적차수",
    accessor: "cumulativeOrder",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "number",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "아이템명",
    accessor: "itemName",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "키워드",
    accessor: "keyword",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "매체",
    accessor: "media",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "서비스명",
    accessor: "service",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "형태",
    accessor: "form",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "플랜",
    accessor: "plan",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "가격",
    accessor: "price",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "number",
    tableType: "won",
    formType: "won",
  },
  {
    Header: "수량",
    accessor: "amount",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "number",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "할인률",
    accessor: "discountRate",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "number",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "수수료",
    accessor: "commisstion",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "number",
    tableType: "won",
    formType: "won",
  },
  {
    Header: "광고비",
    accessor: "advertisingCost",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "number",
    tableType: "won",
    formType: "won",
  },
  {
    Header: "캠페인 담당자",
    accessor: "campaignManagers",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "판매 담당자",
    accessor: "salesManager",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "태그",
    accessor: "tags",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
  {
    Header: "dataId",
    accessor: "id",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    mutationType: "string",
    tableType: "string",
    formType: "string",
  },
];

export const rawCampaignColumnsData = atom({
  key: "rawCampaignColumnsData",
  default: campaignColumnsDefault,
});
export const campaignColumnsData = atom({
  key: "campaignColumnsData",
  default: campaignColumnsDefault,
});

export const useCampaignColumnsDataOnChange = () => {
  const [campaignColumnsDataState, setCampaignColumnsDataState] =
    useRecoilState(campaignColumnsData);

  const onChange = (e, id) => {
    setCampaignColumnsDataState((columnsData) =>
      columnsData.map((val, idx) =>
        idx === id ? { ...val, value: e.target.value } : val
      )
    );
  };
  return onChange;
};
