export const instaUserColumns = [
  "createdAt",

  "nameId",
  "insta_NumberOfFollowers",
  "gender",
  "job",
  "insta_canMakeVideo",
  "insta_category1",
  "insta_category2",
  "insta_style",
  "insta_professionalPoint",
  "insta_heathyPoint",
  "creditPoint",
  "qualitativePoint",
  "economyPoint",
  "insta_numberOfProposals",
  "insta_participationRate",

  "isInstaUser",
  "isNaverUser",
  "isJoinedInPlusBuddy",
  "insta_isExisted",
  "insta_id",
  "insta_designatedPrice",

  "email",
  "password",
  "passwordCheck",
  "name",
  "phoneNumber",
  "additionalEmail",
  "address",
  "bank",
  "accountNumber",
  "residentRegistrationNumber",
  "tags",

  "id",
];
