import { atom, useRecoilState } from "recoil";
import { IColumn } from "../../../3organisms/Org_adminTable2/interface_column";

export const itemColumnsDefault: IColumn[] = [
  {
    Header: "생성일",
    accessor: "createdAt",
    width: 87,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "date",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "카테고리1",
    accessor: "itemCategory1",
    width: 250,
    sortDescFirst: true,
    value: "",
    selected: true,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "서비스명",
    accessor: "itemName",
    width: 200,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "상세정보",
    accessor: "detailInfo",
    width: 200,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "array",
    formType_create: "array",
    formType_edit: "array",
    mutationType_create: "array",
    mutationType_edit: "array",
    editable: true,
  },
  {
    Header: "가격",
    accessor: "price",
    width: 130,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "won",
    formType_create: "won",
    formType_edit: "won",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
  },
  {
    Header: "할인율",
    accessor: "discountRate",
    width: 80,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "number",
    formType_edit: "number",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
  },
  {
    Header: "유형",
    accessor: "type",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "dataId",
    accessor: "id",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "number",
    editable: false,
  },
];

export const rawItemColumnsData = atom({
  key: "rawItemColumnsData",
  default: itemColumnsDefault,
});
