import { atom, useRecoilState } from "recoil";
import { IColumn } from "../../../3organisms/Org_adminTable2/interface_column";
import { dateSmall } from "/home/app/components/3organisms/Org_adminTable/fn_DateSmall";

const nowDate = dateSmall(new Date());
export const campaignParticipationColumnsDefault: IColumn[] = [
  {
    Header: "생성일",
    accessor: "createdAt",
    width: 87,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "date",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "크리에이터명(R)",
    accessor: "creatorNameId",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: true,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "브랜드명(R)",
    accessor: "brandName_partner",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "누적차수",
    accessor: "cumulativeOrder",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "아이템명",
    accessor: "itemName",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "키워드",
    accessor: "keyword",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "hidden",
    editable: false,
  },
  {
    Header: "원고료",
    accessor: "manuscriptFee",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "won",
    formType_create: "won",
    formType_edit: "won",
    mutationType_create: "number",
    mutationType_edit: "number",
    editable: true,
  },
  {
    Header: "제안",
    accessor: "proposal",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "승락",
    accessor: "consent",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "가이드",
    accessor: "guide",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "플랜",
    accessor: "plan",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "string",
    formType_create: "string",
    formType_edit: "string",
    mutationType_create: "string",
    mutationType_edit: "string",
    editable: true,
  },
  {
    Header: "세금신고여부",
    accessor: "isFileTaxes",
    width: 150,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "boolean",
    formType_create: "boolean",
    formType_edit: "boolean",
    mutationType_create: "boolean",
    mutationType_edit: "boolean",
    editable: true,
  },
  {
    Header: "dataId",
    accessor: "id",
    width: 0,
    sortDescFirst: true,
    value: "",
    selected: false,
    tableType: "hidden",
    formType_create: "hidden",
    formType_edit: "hidden",
    mutationType_create: "hidden",
    mutationType_edit: "number",
    editable: false,
  },
];

export const rawCampaignParticipationColumnsData = atom({
  key: "rawCampaignParticipationColumnsData",
  default: campaignParticipationColumnsDefault,
});
